version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: cafeteria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/03_migrate.sql
      - ./db/04_reports_vw.sql:/docker-entrypoint-initdb.d/04_reports_vw.sql
      - ./db/05_roles.sql:/docker-entrypoint-initdb.d/05_roles.sql


  web:
    build:
      context: ./cafeteria
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: app_user
      DB_PASSWORD: app_pass
      DB_NAME: cafeteria_db

volumes:
  pgdata: